package lox;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class Expr {
  interface Visitor<R> {
    R visitAssignExpr(Assign expr);
    R visitBinaryExpr(Binary expr);
    R visitCallExpr(Call expr);
    R visitGetExpr(Get expr);
    R visitGroupingExpr(Grouping expr);
    R visitLiteralExpr(Literal expr);
    R visitLogicalExpr(Logical expr);
    R visitSetExpr(Set expr);
    R visitSuperExpr(Super expr);
    R visitThisExpr(This expr);
    R visitUnaryExpr(Unary expr);
    R visitVariableExpr(Variable expr);
    R visitIndexExpr(Index expr);
    R visitSetIndexExpr(SetIndex expr);
  }
  static class Assign extends Expr {
    Assign(Token name, Expr value) {
      this.name = name;
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitAssignExpr(this);
    }

    final Token name;
    final Expr value;

    @Override
    public String toString() {
      return "Assign(" + name + ", " + value + ")";
    }
  }
  static class Binary extends Expr {
    Binary(Expr left, Token operator, Expr right) {
      this.left = left;
      this.operator = operator;
      this.right = right;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitBinaryExpr(this);
    }

    final Expr left;
    final Token operator;
    final Expr right;

    @Override
    public String toString() {
      return "Binary(" + left + ", " + operator + ", " + right + ")";
    }
  }
  static class Call extends Expr {
    Call(Expr callee, Token paren, List<Expr> arguments) {
      this.callee = callee;
      this.paren = paren;
      this.arguments = arguments;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitCallExpr(this);
    }

    final Expr callee;
    final Token paren;
    final List<Expr> arguments;

    @Override
    public String toString() {
      return "Call(" + callee + ", " + paren + ", " + arguments + ")";
    }
  }
  static class Get extends Expr {
    Get(Expr object, Token name) {
      this.object = object;
      this.name = name;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitGetExpr(this);
    }

    final Expr object;
    final Token name;

    @Override
    public String toString() {
      return "Get(" + object + ", " + name + ")";
    }
  }
  static class Grouping extends Expr {
    Grouping(Expr expression) {
      this.expression = expression;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitGroupingExpr(this);
    }

    final Expr expression;

    @Override
    public String toString() {
      return "Grouping(" + expression + ")";
    }
  }
  static class Literal extends Expr {
    Literal(Object value) {
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitLiteralExpr(this);
    }

    final Object value;

    @Override
    public String toString() {
      return "Literal(" + value + ")";
    }
  }
  static class Logical extends Expr {
    Logical(Expr left, Token operator, Expr right) {
      this.left = left;
      this.operator = operator;
      this.right = right;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitLogicalExpr(this);
    }

    final Expr left;
    final Token operator;
    final Expr right;

    @Override
    public String toString() {
      return "Logical(" + left + ", " + operator + ", " + right + ")";
    }
  }
  static class Set extends Expr {
    Set(Expr object, Token name, Expr value) {
      this.object = object;
      this.name = name;
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitSetExpr(this);
    }

    final Expr object;
    final Token name;
    final Expr value;

    @Override
    public String toString() {
      return "Set(" + object + ", " + name + ", " + value + ")";
    }
  }
  static class Super extends Expr {
    Super(Token keyword, Token method) {
      this.keyword = keyword;
      this.method = method;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitSuperExpr(this);
    }

    final Token keyword;
    final Token method;

    @Override
    public String toString() {
      return "Super(" + keyword + ", " + method + ")";
    }
  }
  static class This extends Expr {
    This(Token keyword) {
      this.keyword = keyword;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitThisExpr(this);
    }

    final Token keyword;

    @Override
    public String toString() {
      return "This(" + keyword + ")";
    }
  }
  static class Unary extends Expr {
    Unary(Token operator, Expr right) {
      this.operator = operator;
      this.right = right;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitUnaryExpr(this);
    }

    final Token operator;
    final Expr right;

    @Override
    public String toString() {
      return "Unary(" + operator + ", " + right + ")";
    }
  }
  static class Variable extends Expr {
    Variable(Token name) {
      this.name = name;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitVariableExpr(this);
    }

    final Token name;

    @Override
    public String toString() {
      return "Variable(" + name + ")";
    }
  }
  
  static class Index extends Expr {
    final Expr array;
    final Expr index;
    Index(Expr array, Expr index) {
      this.array = array;
      this.index = index;

    }
      @Override
      <R> R accept(Visitor<R> visitor) {
        return visitor.visitIndexExpr(this);
      }
  }

  static class SetIndex extends Expr {
    final Expr array;
    final Expr index;
    final Expr value;
    SetIndex(Expr array, Expr index, Expr value) {
      this.array = array;
      this.index = index;
      this.value = value;
    }
      @Override
      <R> R accept(Visitor<R> visitor) {
        return visitor.visitSetIndexExpr(this);
      }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
